import os
import sys
import json
import re

COOKIE_FILE = os.path.join(os.getcwd(), "tiktok_cookies.txt")

def get_saved_cookie_raw():
    if os.path.exists(COOKIE_FILE):
        try:
            with open(COOKIE_FILE, "r", encoding="utf-8") as f:
                return f.read()
        except Exception:
            return ""
    return ""

def parse_cookie_string(raw_str):
    """
    Parses various cookie inputs:
    - Raw key=value; key2=val2 string
    - Single sessionid (e.g. sessionid=abc1234 or just abc1234)
    - Netscape format (.tiktok.com TRUE / FALSE ...)
    """
    raw_str = raw_str.strip()
    if not raw_str:
        return {}

    cookies_dict = {}

    # Check if Netscape cookies.txt format
    if "\t" in raw_str:
        for line in raw_str.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) >= 7:
                name = parts[5].strip()
                val = parts[6].strip()
                cookies_dict[name] = val
        if cookies_dict:
            return cookies_dict

    # Check if raw HTTP Cookie header (key=value; key2=value2)
    pairs = re.findall(r'([^=;\s]+)=([^;]+)', raw_str)
    if pairs:
        for k, v in pairs:
            cookies_dict[k.strip()] = v.strip()
        return cookies_dict

    # If user just pasted the sessionid value directly
    if len(raw_str) >= 20 and not "=" in raw_str:
        cookies_dict["sessionid"] = raw_str
        return cookies_dict

    return cookies_dict

def save_cookies(raw_str):
    """Saves cookie string in Netscape format for yt-dlp and raw string."""
    cookies_dict = parse_cookie_string(raw_str)
    if not cookies_dict:
        return {"success": False, "error": "Invalid cookie format"}

    # Write Netscape format to tiktok_cookies.txt
    lines = ["# Netscape HTTP Cookie File", "# Generated by BT-Dubber Studio", ""]
    for k, v in cookies_dict.items():
        lines.append(f".tiktok.com\tTRUE\t/\tTRUE\t2147483647\t{k}\t{v}")

    with open(COOKIE_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return {
        "success": True,
        "cookieCount": len(cookies_dict),
        "hasSessionId": "sessionid" in cookies_dict,
        "keys": list(cookies_dict.keys())
    }

def check_status():
    raw = get_saved_cookie_raw()
    cookies_dict = parse_cookie_string(raw)
    return {
        "isLoggedIn": len(cookies_dict) > 0 and ("sessionid" in cookies_dict or "sid_guard" in cookies_dict or len(cookies_dict) >= 2),
        "cookieCount": len(cookies_dict),
        "hasSessionId": "sessionid" in cookies_dict,
        "keys": list(cookies_dict.keys())
    }

if __name__ == "__main__":
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd == "status":
            print(json.dumps(check_status(), ensure_ascii=False))
        elif cmd == "save" and len(sys.argv) > 2:
            print(json.dumps(save_cookies(sys.argv[2]), ensure_ascii=False))
        elif cmd == "clear":
            if os.path.exists(COOKIE_FILE):
                os.remove(COOKIE_FILE)
            print(json.dumps({"success": True, "message": "Cookies cleared"}))
    else:
        print(json.dumps(check_status(), ensure_ascii=False))
